### ISSUE TITLE
Sometimes Hex strings really are Hexadecimal, and thus shouldn't be quoted, thus the generated QR code ends up wrong.

### ISSUE THREAD

**Issue by MailYouLater** [evgeni/qifi#4]
I'm not too sure where the issue lies exactly, but I've noticed that some of the Wi-Fi networks I've tried to generate QR codes for on [QiFi.org](http://qifi.org) have ended up with QR codes that don't work because the data in the QR code has quotes (") in places where it shouldn't (I've seen WIFI:S:<SSID>;T:WPA;P:"<KEY>" and WIFI:S:"<SSID>";T:WPA;P:"<KEY>"). If I scan the generated QR code, then manually write what my QR code reader shows into another QR code generator, but remove the spurious quotes, then that QR code works, but that kind of defeats the purpose of QiFi doesn't it?

Hopefully it's a fairly easy thing to fix, but I don't know, I haven't looked at the code.

In case it matters, I'm using Firefox 39.0 on Windows 7 Home Premium x64 to use the site and the "[Barcode Scanner](https://play.google.com/store/apps/details?id=com.google.zxing.client.android)" app by [ZXing (Zebra Crossing)](http://zxing.github.io/zxing) to read the barcode.

**Comment by MailYouLater** [comment]
I fiddled around with the site for a while to see if there's a discernible pattern, and I think I found one.
If I have only characters which used in writing hexadecimal (i.e. 0-9 and a-f) I get quotes around that string (SSID or Key, doesn't matter), however if I add a character that isn't used in writing hexadecimal (e.g. g-z, !@#$... etc.) then the quotes don't get added.

**Comment by MailYouLater** [comment]
... OK that's weird.
Having now looked at the code, it looks like this is done on purpose. So I checked the documentation (by the way, your link to the documentation should be changed to https://github.com/zxing/zxing/wiki/Barcode-Contents#wifi-network-config-android) and for both SSID and Password it says "Enclose in double quotes if it is an ASCII name, but could be interpreted as hex" which makes perfect sense, except that in my case the router seems to be using hex, not 'ASCII that could be interpreted as hex'. Thus it's not very useful in this situation. I'm not sure how this should be handled, but I'm sure I'm not the only one who this won't work for.

Thanks for taking the time to read this, Hopefully you can fix this somehow.

I'll change the title to reflect my findings.

**Comment by evgeni** [comment]
Hi @MailYouLater!

Thanks a lot for the detailed report!
Yes, the current behaviour is intentional as I thought that having a literal "ABCD" is more common than it being interpreted as HEX.

I'll think about how to fix it properly -- I'd prefer not to add another checkbox to the UI if not really needed.

**Comment by evgeni** [comment]
Hey again,

just wondering: is this happening to you for the WPA PSK or for the SSID?

**Comment by evgeni** [comment]
@MailYouLater ping? any update on this?

**Comment by MailYouLater** [comment]
Hello,
Sorry I didn't get back to you. (I don't use GitHub much.)
Anyway, I don't remember for a certainty any details about what was happening that I didn't put in the post, but I just did a comparison of what QiFi.org currently generates (as of 02/25/2016) vs a working QR code I generated around when I posted the issue, (I don't remember what tool I used to generate it, but it works for letting people onto the WiFi network in question.) and the difference between the two is that the WEP Password is quoted in the one QiFi.org generates, but not in the working one.

Thanks for looking into this, and once again, I'm so sorry I didn't get back to you earlier.

**Comment by frizbee** [comment]
Hey, thanks, this is really cool idea. I have similar problem, It generates string with quotes around password. When I get this pattern `WIFI:S:<SSID>;T:<WPA|WEP|>;P:<password>;;` and generate with third party online qr generator, it worked perfectly.

**Comment by greecemunky** [comment]
I've recently used [QiFi](http://qifi.org/) too and have had the same or similar issue.  On Apple iOS 11.2.5 (current latest), using the Camera app to scan the generated QR code, it fails to join the network - I assume due to the quotes being interpreted literally (quotes seen when scanned using iOS app QR Reader).  The password is presently all numbers, used for a guest network.

The same QR code works with [ZXing's Barcode Scanner](https://play.google.com/store/apps/details?id=com.google.zxing.client.android) on Android.

Manually creating a QR code with [qrencode](https://github.com/fukuchi/libqrencode) using the syntax outlined on QiFi (same as frizbee mentioned above) works with the same Apple iOS Camera app (no quotes).

Reading [Barcode-Contents](https://github.com/zxing/zxing/wiki/Barcode-Contents), based on the "Wifi Network config (Android)" explanation, it appears QiFi is operating as per the "spec"

> Enclose in double quotes if it is an ASCII name, but could be interpreted as hex (i.e. "ABCD")

so it appears Apple iOS isn't following that spec.  But, isn't the WPA-PSK ASCII passphrase maximum length 63 characters, and hexadecimal keys _must_ be 64 characters?  If so, there should not be a requirement to wrap ASCII passwords in double-quotes.  Maybe Apple iOS uses this logic when determining what type of key is assumed to be presented, and does not expect double quotes to be used as enclosures.

EDIT:  Sorry, I see this has already been dealt with with [this commit](https://github.com/evgeni/qifi/commit/b7226fbcf35e57bc39889ea2b7466efcc3574ab0), but [QiFi](http://qifi.org/) has not yet been updated.

**Comment by evgeni** [comment]
@greecemunky yeah, the preview page at https://evgeni.github.io/qifi/ is updated, but I did not update qifi.org yet. can you confirm the preview works for you?

**Comment by greecemunky** [comment]
@evgeni Yes, the preview page appears to be working as expected.  Thanks.

**Comment by evgeni** [comment]
closing as fixed thanks
